//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitiyEntity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    public partial class ProductDetail
    {
        public int id { get; set; }
        public string name { get; set; }
        [DisplayName("Upload Image")]
        public string img { get; set; }
        public Nullable<decimal> price { get; set; }
        public string ip { get; set; }
        public HttpPostedFileBase imagefile { get; set; }
    }
}
